#!/usr/bin/env bash

set -e

env=${APP_ENV=production}

# Ensure /.composer exists and is writable
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

# Run a command or supervisord
if [ $# -gt 0 ];then
    # If we passed a command, run it as current user
    exec "$@"
else
    # Otherwise start supervisord
    /usr/bin/supervisord
fi


if [ "$env" != 'local' ]
    echo "Caching Configuration"
    (
        cd /var/www/html &&
        php artisan config:cache && 
        php artisan route:cache &&
        php artisan view:cache &&
        php artisan optimize
    )
fi