version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    ports:
     - "80:80"
    working_dir: /var/www/html
    environment:
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
    volumes:
     - .:/var/www/html
    networks:
     - cpnet
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    user: node
    volumes:
     - .:/var/www/html
    networks:
     - cpnet
  npm:
    image: node:latest
    volumes:
      - .:/var/www/html
    networks:
      - cpnet
    working_dir: /var/www/html
  vuecli:
    build:
      context: ./docker/vuecli
      dockerfile: Dockerfile
    networks:
    - cpnet
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "password"
    volumes:
     - cpmysql:/var/lib/mysql
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - cpnet
  redis:
    image: redis:alpine
    volumes:
     - cpredis:/data
    networks:
     - cpnet
  adminer:
    image: adminer
    restart: always
    ports:
     - 8090:8080
    networks:
     - cpnet
networks:
  cpnet:
    driver: "bridge"
volumes:
  cpmysql:
    driver: "local"
  cpredis:
    driver: "local"